# Generated by Django 4.2.3 on 2024-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=50)),
                ("question", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Users that contacted",
            },
        ),
    ]
