# Generated by Django 4.2.3 on 2024-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_user_country_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
