# Generated by Django 4.2.3 on 2024-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0005_user_full_name_alter_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(default="Haircut", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="This is the haircut", null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("business_name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("company_type", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
                ("company_needs", models.ManyToManyField(to="userauths.service")),
            ],
        ),
    ]
