# Generated by Django 4.2.3 on 2024-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0006_service_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(default="Project management", max_length=100),
        ),
    ]
