# Generated by Django 4.2.3 on 2024-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_alter_service_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, default="This is the service", null=True
            ),
        ),
    ]
