# Generated by Django 4.2.3 on 2024-02-21 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_alter_service_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name_plural": "Clients Booking"},
        ),
    ]
