# Generated by Django 4.2.3 on 2024-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_blog_blog_title_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
