# Generated by Django 4.2.3 on 2024-02-09 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_review_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="wishlist",
        ),
    ]
