# Generated by Django 4.2.3 on 2024-02-09 11:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_page_image",
            field=models.ImageField(
                default="blog-img.jpg", upload_to=core.models.user_directory_path
            ),
        ),
    ]
