# Generated by Django 4.2.3 on 2024-02-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_blog_blog_page_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="bid",
            new_name="eid",
        ),
        migrations.CreateModel(
            name="EventImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        default="event-img.jpg", upload_to="event-images"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_images",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Events images",
            },
        ),
    ]
