# Generated by Django 4.2.3 on 2024-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_bid_event_eid_eventimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default="Case study ", null=True),
        ),
    ]
