# Generated by Django 4.2.3 on 2024-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_discussion",
            field=models.CharField(
                default="Small UK merchants, businesses, and other enterprises can now use Tap to Pay on service to replace payment terminals at point of sale",
                max_length=200,
            ),
        ),
    ]
