# Generated by Django 4.2.3 on 2024-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_event_event_discussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="main_page_title",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_discussion",
            field=models.CharField(default="", max_length=150),
        ),
    ]
