# Generated by Django 4.2.3 on 2024-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_event_main_page_title_alter_event_event_discussion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_date",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_date",
            new_name="start_time",
        ),
    ]
