# Generated by Django 4.2.3 on 2024-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_end_date_event_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
