# Generated by Django 4.2.3 on 2024-02-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_blog_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, default="Case study ", null=True),
        ),
    ]
