# Generated by Django 4.2.3 on 2024-02-09 21:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="Case study ", null=True
            ),
        ),
    ]
