# Generated by Django 4.2.3 on 2024-02-09 21:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_event_eid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="eid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=40,
                prefix="",
                unique=True,
            ),
        ),
    ]
