# Generated by Django 4.2.3 on 2024-04-23 04:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_blog_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_page_image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="blog",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
